name: 'renovate-config-validator'
description: 'Validate Renovate config in GitHub Actions'
inputs:
  pattern:
    description: 'Regular expression for filename to validate, default to *.json'
    required: false
    default: '*.json'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'green'
